services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: scan_and_dine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  db-viewer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  postgres_data: 