spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/scan_and_dine
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: path-pattern-parser
  web:
    resources:
      add-mappings: false
server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false
